### ISSUE TITLE
TypeError: increase_indent() got an unexpected keyword argument 'indentless' while rebuilding map

### ISSUE THREAD

**Issue by zerwes** [zerwes/ansible-fqcn-converter#9]
???
```
Traceback (most recent call last):
  File "/home/zerwes/git/ansible-fqcn-converter/./fqcn-fixer.py", line 227, in <module>
    yaml.dump(
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/usr/lib/python3/dist-packages/yaml/representer.py", line 28, in represent
    self.serialize(node)
  File "/usr/lib/python3/dist-packages/yaml/serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "/usr/lib/python3/dist-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/lib/python3/dist-packages/yaml/serializer.py", line 100, in serialize_node
    self.emit(SequenceEndEvent())
  File "/usr/lib/python3/dist-packages/yaml/emitter.py", line 115, in emit
    self.state()
  File "/usr/lib/python3/dist-packages/yaml/emitter.py", line 412, in expect_block_mapping_simple_value
    self.expect_node(mapping=True)
  File "/usr/lib/python3/dist-packages/yaml/emitter.py", line 250, in expect_node
    self.expect_block_sequence()
  File "/usr/lib/python3/dist-packages/yaml/emitter.py", line 370, in expect_block_sequence
    self.increase_indent(flow=False, indentless=indentless)
TypeError: increase_indent() got an unexpected keyword argument 'indentless'
```

**Comment by zerwes** [comment]
```
~/git/ansible-fqcn-converter bb250ba+* ± git bisect good
40a757e6ad2b601769b4f96ad2dc61e8f59771e8 is the first bad commit
commit 40a757e6ad2b601769b4f96ad2dc61e8f59771e8
Author: Klaus Zerwes <zerwes@users.noreply.github.com>
Date:   Thu Sep 8 15:28:18 2022 +0200

    fixed warn condition and linted Dumper

 fqcn-fixer.py | 9 +++++----
 1 file changed, 5 insertions(+), 4 deletions(-)
```
```diff
~/git/ansible-fqcn-converter bb250ba+* ± git show 40a757e6ad2b601769b4f96ad2dc61e8f59771e8
commit 40a757e6ad2b601769b4f96ad2dc61e8f59771e8 (refs/bisect/bad)
Author: Klaus Zerwes <zerwes@users.noreply.github.com>
Date:   Thu Sep 8 15:28:18 2022 +0200

    fixed warn condition and linted Dumper

diff --git a/fqcn-fixer.py b/fqcn-fixer.py
index 68c2852..d780b49 100755
--- a/fqcn-fixer.py
+++ b/fqcn-fixer.py
@@ -35,9 +35,10 @@ def isexcluded(path, _exclude_paths):
         fnmatch.fnmatch(ppath, ep)
         for ep in _exclude_paths
         )
-class Dumper(yaml.Dumper):
-    def increase_indent(self, flow=False, *args, **kwargs):
-        return super().increase_indent(flow=flow, indentless=False)
+class Dumper(yaml.Dumper): # pylint: disable=too-many-ancestors
+    """https://github.com/yaml/pyyaml/issues/234"""
+    def increase_indent(self, flow=False, *dargs): # pylint: disable=keyword-arg-before-vararg
+        return super().increase_indent(dargs, indentless=False)
 
 basepath = os.path.dirname(os.path.realpath(__file__))
 
@@ -262,7 +263,7 @@ for f in parsefiles:
                     print('.', file=sys.stderr, end='', flush=True)
                 else:
                     print('*', file=sys.stderr, end='', flush=True)
-                    if len(fqcndict[fqcnmodule]) > 0:
+                    if len(fqcndict[fqcnmodule]) > 1:
                         warnings.append(
                             'alternative replacement of %s : %s' %
                             (fqcnmodule, ' | '.join(fqcndict[fqcnmodule]),)
```
